import Open_sans from "@/services/FontSecondary";
import "./globals.css";
import { AppContextProvider } from "@/lib/AppContext";

export const metadata = {
  title: "Franchise RE/MAX Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body className={Open_sans.className}>{children}</body>
      </AppContextProvider>
    </html>
  );
}
